### PR TITLE
Fix minor import & pd.unique calling failed bugs

### PR DESCRIPTION
**Pull request by mindon**
it's my env (python v2.7 with keras v1.2.1) problem, requires python 3.5+ and keras 2+

### CODE REVIEW

**Comment by tae-jun** [comment]
@mindon Thanks! You are the first and only one that sent a PR 😄 

Why did you close? Is it resolved?

**Comment by mindon** [comment]
met some other issues due to the keras v1.2.1.. :sob: . not quite sure if these are also caused by the env of the machine. will update later...  :+1:

**Comment by tae-jun** [comment]
@mindon Oh 😢 Try keras v2.0.4 and pandas v0.19.2
These are the versions that I used :)

**Comment by mindon** [comment]
@tae-jun  the pd.unique issue is found under pandas v0.21.0 with python2.7

**Pull request closed without merging**
