### PR TITLE
Clear errors running with pandas v0.21.0

### PR DESCRIPTION
**Pull request by mindon**
1.  fix pd.unique issue under pandas v0.21.0
2.  fix self.constraints failed error

with python v3.6.3 / keras v2.0.9 / pandas v0.21.0

### CODE REVIEW

**Comment by tae-jun** [comment]
@mindon Thanks for your contribution! 😄

**Comment by mindon** [comment]
it's such a great thing you shared this project here, thank u for your work.
btw, would u share what's the purpose of self.constraints? and how its value should be?

**Comment by tae-jun** [comment]
@mindon Thanks! 😄 You made my day :)

Actually, I don't know 😢 I just watched internal source of Keras' class `Model` and modified it so that it can be run on TFRecords. If you want to understand it, you should read carefully the internal source of `Model`.  I also tried it, but I just gave up and made it work first.

FYI, if you have a further interest at music auto-tagging, you may read our paper (https://arxiv.org/abs/1710.10451). 
The author of this repository model (sample-cnn) and I improved the model. (0.9113 on MTAT)
The codes and models will be published here soon (maybe in two weeks?): https://github.com/tae-jun/resemul

Thanks for your heavy contribution! 👍

**Comment by mindon** [comment]
@tae-jun forget the "constaints" question :smile: 
 it's the paper lead me to your code. :+1:
watching your new project :smiley:  thanks for your answer in detail :tea:

**Comment by tae-jun** [comment]
@mindon Thanks! I also appreciate your contribution 😄

**Pull request merged**
